name: workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v1
      with: { go-version: 1.14 }

    - name: Install Terraform
      run: |
        curl -sL https://releases.hashicorp.com/terraform/0.12.21/terraform_0.12.21_linux_amd64.zip -o terraform.zip
        sudo unzip terraform.zip -d /usr/bin && rm -f terraform.zip

    - name: Install Taskfile
      run: curl -sL https://taskfile.dev/install.sh | sh

    - name: Run tests
      run: ./bin/task test
